name: CI

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+*' #si considerano solo i tag del tipo v1.2.0
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Put back the git branch into git (Earthly uses it for tagging)
      run: |
        branch=""
        if [ -n "$GITHUB_HEAD_REF" ]; then
          branch="$GITHUB_HEAD_REF"
        else
          branch="${GITHUB_REF##*/}"
        fi
        git checkout -b "$branch" || true
    - name: Download latest earthly
      run: "sudo /bin/sh -c 'wget https://github.com/earthly/earthly/releases/download/v0.5.11/earthly-linux-amd64 -O /usr/local/bin/earthly && chmod +x /usr/local/bin/earthly'"
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ secrets.CI_USER }}
        password: ${{ secrets.CI_PAT }}
    - name: Run build
      run: earthly +all
    - name: Tag image server
      run: docker tag gdr ghcr.io/mind-informatica-srl/gdr:${GITHUB_REF##*/}
    - name: Push server
      run: docker push ghcr.io/mind-informatica-srl/gdr:${GITHUB_REF##*/}
    - name: Tag image bootstrap
      run: docker tag gdr-bootstrap ghcr.io/mind-informatica-srl/gdr-bootstrap:${GITHUB_REF##*/}
    - name: Push bootstrap
      run: docker push ghcr.io/mind-informatica-srl/gdr-bootstrap:${GITHUB_REF##*/}